name: Trigger KV cache and Kafka on Unpublish events

on: 
  repository_dispatch:
    types:
      - resource-unpublished
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Status: ${{ github.event.client_payload.status }}"
        echo "Path: ${{ github.event.client_payload.path }}"
  trigger:
    if: (github.event.client_payload.status == 200 || github.event.client_payload.status == 204) && endsWith(github.event.client_payload.path, '.json')
    runs-on: ubuntu-latest
    steps:
    - run: | 
        echo "DELETE_ENDPOINT=${{ secrets.CF_WORKER_ENDPOINT }}${{ github.event.client_payload.path }}/delete" >> $GITHUB_ENV
    - run: | 
        curl --location --request POST '${{ env.DELETE_ENDPOINT }}' \
          --header 'Content-Type: application/json'    
    - run: | 
        curl --location --request POST '${{ secrets.KAFKA_TEST_ONDEMAND_ENDPOINT }}' \
          --header 'Content-Type: application/json' \
          --header 'AppKey: ${{ secrets.KAFKA_APPKEY }}' \
          --data-raw '{
            "paths" : ["${{ github.event.client_payload.path }}"]
          }'